config/routes.rb
Rails.application.routes.draw do

  patch 'users/:user_id/preference', to: 'users#preference',  as: "preference"

  get 'admin/index'

  get 'payments/new', as: "new_payment"

  post 'payments/create', as: "payments"

  resources :users, only: [:edit, :update, :show]

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  post '/room/:rid', to: 'streams#host', as: "host"

  get '/room/:rid', to: 'streams#guest', as: "guest"

  post '/summary', to: 'streams#summary', as: "summary"


  root 'welcome#index'

	get 'users/index'
  # get 'welcome/index'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  mount_uploaders :avatars, AvatarUploader

  has_many :payments
  has_many :authentications, :dependent => :destroy
  has_and_belongs_to_many :interests
  has_and_belongs_to_many :teach_languages
  has_and_belongs_to_many :learn_languages

  # validates :first_name, presence: true
  # validates :last_name, presence: true
  # validates :gender, presence: true
  # validates :age, numericality: { greater_than: 18, only_integer: true }

  # validates :email, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}, presence: true


  def self.create_with_auth_and_hash(authentication,auth_hash)

    create! do |u|
      completename = auth_hash["info"]["name"]
      u.first_name = completename.split(" ").first
      u.last_name = completename.split(" ").last
      u.email = auth_hash["extra"]["raw_info"]["email"]
      u.gender = "unknown"
      u.age = 99999
      u.password = SecureRandom.hex(6)
      u.authentications<<(authentication)
    end
  end

  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end

  def password_optional?
    true
  end


def online?
  updated_at > 5.minutes.ago
end

end

app/controllers/clearance/users_controller.rb
class Clearance::UsersController < Clearance::BaseController
  if respond_to?(:before_action)
    before_action :redirect_signed_in_users, only: [:create, :new]
    skip_before_action :require_login, only: [:create, :new], raise: false
    skip_before_action :authorize, only: [:create, :new], raise: false
  else
    before_filter :redirect_signed_in_users, only: [:create, :new]
    skip_before_filter :require_login, only: [:create, :new], raise: false
    skip_before_filter :authorize, only: [:create, :new], raise: false
  end

  def new
    @user = user_from_params
    render template: "users/new"
  end

  def create
      @user = user_from_params

    if @user.save
      sign_in @user
      redirect_back_or url_after_create
    else
      redirect_back
      render template: "users/new"
    end
  end

  private

  def avoid_sign_in
    warn "[DEPRECATION] Clearance's `avoid_sign_in` before_filter is " +
      "deprecated. Use `redirect_signed_in_users` instead. " +
      "Be sure to update any instances of `skip_before_filter :avoid_sign_in`" +
      " or `skip_before_action :avoid_sign_in` as well"
    redirect_signed_in_users
  end

  def redirect_signed_in_users
    if signed_in?
      redirect_to Clearance.configuration.redirect_url
    end
  end

  def url_after_create
    Clearance.configuration.redirect_url
  end

  def user_from_params
    email = user_params.delete(:email)
    password = user_params.delete(:password)
    first_name = user_params.delete(:first_name)
    last_name = user_params.delete(:last_name)
    gender = user_params.delete(:gender)
    age = user_params.delete(:age)

    Clearance.configuration.user_model.new(user_params).tap do |user|
      user.email = email
      user.password = password
      user.first_name = first_name
      user.last_name = last_name
      user.age = age
      user.gender = gender
    end
  end

  def user_params
    params[Clearance.configuration.user_parameter] || Hash.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = current_user

    @user_interests = current_user.interests.all

    @user_teach_languages = current_user.teach_languages

    @user_learn_languages = current_user.learn_languages

    @chats_join = Stream.all.where(guest_id:current_user.id)
    @chats_host = Stream.all.where(host_id:current_user.id)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    if current_user.nil?
      redirect_to root_url
    else
     render :edit
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)

        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def preference
    languages = Language.all
    @user = current_user
        languages_t = params["user"]["teach_languages"]

        if languages_t.nil?
        else

              if TeachLanguage.find_by(name: languages_t).nil?
              TeachLanguage.create(name: languages_t)
              end
              a = TeachLanguage.find_by(name: languages_t) 
              a.users << @user
        end

        languages_l = params["user"]["learn_languages"]
        if languages_l.nil?
        else
          
              if LearnLanguage.find_by(name: languages_l).nil?
              LearnLanguage.create(name: languages_l)
              end
              a = LearnLanguage.find_by(name: languages_l) 
              a.users << @user
         end 


        interests = params["user"]["interests"]
        if interests.nil?
        else
          
              if Interest.find_by(name: interests).nil?
              Interest.create(name: interests)
              end
              a = Interest.find_by(name: interests) 
              a.users << @user
        end
       
       redirect_to @user, notice: 'User was successfully updated.'
    
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      # @languages = Language.all.pluck(:name)
      params.require(:user).permit(:last_name, :first_name, :email, :age, :gender, {avatars: []}, :learn_language)
    end
end

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.text_field :first_name, type: 'first_name', placeholder: "First name", :class => "input-full-width" %>
</div>

<div class="text-field">
  <%= form.text_field :last_name, type: 'last_name',placeholder: "Last name", :class => "input-full-width" %>
</div>

<div class="text-field">
  <%= form.text_field :email, type: 'email',placeholder: "Email", :class => "input-full-width" %>
</div>

<%= radio_button("user", "gender", "Male") %>
<%= label_tag(:gender, "Male", :class => "light") %>
<%= radio_button("user", "gender", "Female") %>
<%= label_tag(:gender, "Female", :class => "light") %>

<div class="text-field">
  <%= form.number_field :age, type: 'integer', placeholder: "Age", :class => "input-full-width" %>
</div>

<div class="password-field">
  <%= form.password_field :password,placeholder: "Password", :class => "input-full-width" %>
</div>
<div class="submit-field">
  <%= form.submit :class => "input-full-width full-width-input-primary"%>
</div>

app/views/users/_preference.html.erb
<div class="container">
	<%= form_for @user, url: preference_path(current_user.id)  do |form| %>
		<h3 class="brand-heading">Almost there</h3>
		<div class="signup-choice">
			<p>Please complete the following information so we can match you with people worldwide</p>
			<p class="signup-choice--heading">What is your native language</p>
			<ul class="signup-choice--list">
				<% @languages.each do |x| %>
					<li>
						<%= x.name %> 
						<%= radio_button("user", "teach_languages", x.name) %>
					</li>
				<!-- end for do each -->
				<% end %>	
			</ul>
		</div>
		<div class="signup-choice">
			<p class="signup-choice--heading">What languages are you learning?</p>
			<p>We still don't know what language you want to learn. Check one of the following languages that you want to learn.</p>
			<ul class="signup-choice--list">
				<% @languages.each do |x| %>
					<li>
						<%= x.name %> 
							<%= radio_button("user", "learn_languages", x.name) %>
					</li>
				<% end %>	
			</ul>
		</div>
		<div class="signup-choice">
			<p class="signup-choice--heading">Please select some of the following interests</p>
			<p>Tick the following interest so that we can pair you up with people of similar interest!</p>
			<ul class="signup-choice--list">
				<% @interests.each do |x| %>
					<li>
						<%= x.name %> 
							<%= radio_button("user", "interests", x.name) %>
					</li>
				<% end %>	
			</ul>
		</div>
		<div class="row">
			<div class="col-md-3">
				<%= form.submit :class => "input-full-width full-width-input-primary" %>
			</div>
		</div>
	<% end %>
</div>

app/views/users/_profile_image.html.erb
<strong>Image Profile:</strong>
  <% if @user.avatars[0].nil? %>
    <%= image_tag 'http://www.ccusersforum.org/images/user.png' , :align=> "middle",  class:"img-circle", :size => "180x180" %>
  <% else %>
    <%= image_tag(@user.avatars[0].url , :align=> "middle",  class:"img-circle", :size => "260x180")%>
<% end %>

app/views/users/edit.html.erb
<%= form_for @user, url: user_path  do |f| %>        
  <div class="row">
    <div class="col-sm-4">
      <% if @user.avatars[0].nil? %>
        <div class="profile-img-placeholder">
        </div>
      <% else %>
      <div>
        <%= image_tag (@user.avatars[0].url), :size => "180x180" %>
      </div>
      <% end %>
    </div>
    
    <div class="col-sm-8">
     <!-- style= "min-height: 1200px"> -->

      <p class="profile-img-spacer">
        Upload an image of yourself so other users can see what you look like. Click the choose file button and pick an image.
      </p>
      <%= f.file_field :avatars, multiple: true %>
    </div>
  </div>
	<%= f.label :first_name %>
  <%= f.text_field :first_name, class: 'input-full-width' %>


  <%= f.label :last_name %>
  <%= f.text_field :last_name, class: 'input-full-width' %>


  <%= f.label :email %>
  <%= f.text_field :email, class: 'input-full-width' %>

  <%= f.label :age %>
  <%= f.text_field :age, class: 'input-full-width' %>


  <div class="radio-gender">
    <%= f.label :gender %>
    <div>
      <%= radio_button("user", "gender", "Male") %>
      <%= label_tag(:gender, "Male") %>
      <%= radio_button("user", "gender", "Female") %>
      <%= label_tag(:gender, "Female") %>
    </div>

  </div>

  <%= f.submit class: 'input-full-width full-width-input-primary' %>

<% end %>

app/views/users/new.html.erb
<center><h1>Register</h1></center>

<%= form_for @user do |form| %>
  <%= render partial: 'users/form', object: form %>

 	<p>
		<%= form.file_field :avatars, multiple: true %>
	</p>

 	<p>
  	<% unless @user.avatars[0].nil? %>
	  	<%= image_tag (@user.avatars[0].url) , :align=> "middle",  class:"img-circle", :size => "260x180" %>
	  <% end %>
	</p>

  <div class="submit-field">
    <%= form.submit %>
  </div>

<% end %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', root_path %>

app/views/users/show.html.erb
<% if signed_in? %>
  <div class="container padding-top--sm">
    <div class="row">
      <div class="col-md-2 col-md-offset-1">
        <ul class="nav nav-stacked">
          <li class="active"><a href="#edit-profile" data-toggle="tab">Edit Profile</a></li>
          <li><a href="#conversations" data-toggle="tab">Conversation history</a></li>
          <li><a href="#languages-and-interests" data-toggle="tab">Languages and interests</a></li>
          <li><a href="#coins" data-toggle="tab">Coins</a></li>
        </ul>
      </div>

      <div class="col-md-8">
          <div class="tab-content" style= "min-height: 500px">

            <div class="tab-pane active" id="edit-profile">
              <div class="panel-header">
                <h3>Profile</h3>
              </div>
              <div class="panel-main">
                <%= render template: 'users/edit' %>
              </div>
            </div>
            <div class="tab-pane" id="conversations">
              <div class="panel-header">
                <h3>Conversation history</h3>
              </div>
              <div class="panel-main">
               <strong><p>Chat you hosted before: </p></strong>
                 <ol>
                   <% @chats_host.each do |x| %>
                     <% a = User.find(x.guest_id) %>
                      <% b = User.find(x.host_id) %>
                    <li><%= x.time_start%>, <%= a.first_name %> joined <%= b.first_name %>'s room.  <%= b.first_name%> earned <span class="badge"><%= x.amount %></span>.</li>
                     <%= %>
                   <% end %>
                 </ol>
                <strong><p>Chat you joined before:</p></strong>
                   <ol>
                   <% @chats_join.each do |x| %>
                     <% a = User.find(x.host_id) %>
                      <% b = User.find(x.guest_id) %>
                     <li><%= x.time_start%>, <%= b.first_name %> joined <%= a.first_name %>'s room.  <%= a.first_name%> earned <span class="badge"><%= x.amount %></span>.</li>
                     <%= %>
                   <% end %>
                 </ol>
              </div>
            </div>
            <div class="tab-pane" id="languages-and-interests">
              <div class="panel-header">
                <h3>Languages and interests</h3>
              </div>
              <div class="panel-main">
                <p>
                  <strong>My Interests</strong>
                  <% @user_interests.each do |x| %>
                  <p><%= x.name%></p>
                  <% end %>
                </p>
                <p>
                  <strong>I Speak</strong>
                  <% @user_teach_languages.each do |x| %>
                  <p><%= x.name%></p>
                  <% end %>
                </p>
                <p>
                  <strong>I am learning</strong>
                  <% @user_learn_languages.each do |x| %>
                  <p><%= x.name%></p>
                  <% end %>
                </p>
              </div>
            </div>
            <div class="tab-pane" id="coins">
              <div class="panel-header">
                <h3>Coins</h3>
              </div>
              <div class="panel-main">
                <p>Coins are used when you join a chat as a student. You can earn coins by hosting calls to help out the community, or you can buy coins and start chatting in the language you are learning.</p>
                <p>Top up your coins by picking from the options below</p>
                <%= link_to 'Buy 100 Coins Now' , new_payment_path(current_user.id), class: "btn btn-warning"  %>
                <p class="padding-top--sm">You currently have <span><%= @user.total_coins %></span> coins remaining</p>     
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

<% else %>
  <% redirect_to root_url %>
  
<% end %>