config/routes.rb
Rails.application.routes.draw do

  patch 'users/:user_id/preference', to: 'users#preference',  as: "preference"

  get 'admin/index'

  get 'payments/new', as: "new_payment"

  post 'payments/create', as: "payments"

  resources :users, only: [:edit, :update, :show]

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  post '/room/:rid', to: 'streams#host', as: "host"

  get '/room/:rid', to: 'streams#guest', as: "guest"

  post '/summary', to: 'streams#summary', as: "summary"


  root 'welcome#index'

	get 'users/index'
  # get 'welcome/index'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/stream.rb
class Stream < ApplicationRecord
end

app/controllers/streams_controller.rb
class StreamsController < ApplicationController

  def host
  	rid = params[:rid]
  	apiKey = ENV["API_KEY"]
  	@opentok= OpenTok::OpenTok.new(apiKey, ENV["API_SECRET"])
  	@stream = Stream.find_by(rid: rid)
  	if @stream 
  		sid = @stream.sid
  		token = @opentok.generate_token(sid)
  	else
  		router = @opentok.create_session :archive_mode => :always,:media_mode => :routed
  		sid = router.session_id
      @stream = Stream.new(rid: rid,sid: sid, host_id: params[:host])
      @stream.save!
  		token = @opentok.generate_token(sid)
  	end
    render :room, :locals => {
      :apiKey => apiKey,
      :sid => sid,
      :rid => rid,
      :token => token
    }
  end

  def guest
    gid = params[:guest]
    start= params[:start]
    rid = params[:rid]
    apiKey = ENV["API_KEY"]
    @opentok= OpenTok::OpenTok.new(apiKey, ENV["API_SECRET"])
    @stream = Stream.find_by(rid: rid)
      sid = @stream.sid
      @stream.update(guest_id: gid, time_start: start)
      token = @opentok.generate_token(sid)
    render :room, :locals => {
      :apiKey => apiKey,
      :sid => sid,
      :rid => rid,
      :token => token
    }
  end


  def summary
  	rid = params[:rid]
  	@stream = Stream.find_by(rid: rid)
    if @stream.guest_id == nil
      render :summary
    else
      if @stream.amount == nil
    	@stream.update(time_end: Time.now)
    	@stream.save!
    	@duration = (Time.strptime(@stream.time_end,  '%Y-%m-%d %H:%M:%S %z')) - (Time.strptime(@stream.time_start,  '%Y-%m-%d %H:%M:%S %z'))
    	@amount = @duration.seconds
      @stream.update(amount: @amount)
      @stream.save!
    	@earner = User.find(@stream.host_id)
    	@spender = User.find(@stream.guest_id)
    	@earner.update(total_coins: (@earner.total_coins+@amount))
      @earner.save!
    	@spender.update(total_coins: (@spender.total_coins-@amount))
      @spender.save!
      end
      @earner = User.find(@stream.host_id)
      @spender = User.find(@stream.guest_id)
      @amount = @stream.amount
      @duration = @amount
  	render :summary
    end
  end
  
end

app/helpers/streams_helper.rb
module StreamsHelper
end

app/views/streams/index.html.erb
<meta charset="UTF-8">

<meta http-equiv="content-type" content="text/html;charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="chrome=1">
<link href='https://fonts.googleapis.com/css?family=Muli:300,400' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="//tokbox.com/css/shared/fonts.css" />
<link rel="stylesheet" href="/vendors/fontAwesome/css/font-awesome.css" />
<link rel="stylesheet" href="/vendors/bootstrap/css/bootstrap.min.css" />

<script src="//code.jquery.com/jquery-1.10.2.min.js" type="text/javascript"></script>
<script src="/vendors/bootstrap/js/bootstrap.js"></script>

<body>
  <div id="logoContainer"></div>

  <div class="container">

    <div id="insideContainer">
    <a href="http://tokbox.com/?utm_source=opentokrtc&utm_medium=web&utm_campaign=webrtc" id="opentokLogo" target="_blank">
      <img src="/img/img-opentok-logo.png" alt="opentok transparent logo" />
    </a>
      <h1>Welcome to <b>LanguageChat</b></h1>
       <h5>A revolutionary learning experience.</h5> 
       <div id="roomContainer">
        <form> 
        <input id="roomName" class="std-input-text" type="text" placeholder="Enter a room name"/> 
        </form>
         <a href="#" id="submitButton" class="btn-standard actionButton">Join</a>
        <div id = "store_icons">
        </div>
        <div id="infoBox">
          <p>Language Chat allows you to chat with other users from different locations across the globe.</p>
          <p>This application is brought to you by team 2 of the NEXT academy September 2016 Intake. (James, Ben, Damien, Erika</a>.
          </p>
        </div>
      </div>
    </div>
  </div>

  <link rel="stylesheet" href="/css/index.css" />
  <script src="/smartbanner/jquery.smartbanner.js"></script>
  <script src="/js/index.js" type="text/javascript"></script>
  <script src="/app.js" type="text/javascript"></script>
</body>

app/views/streams/room.html.erb
<script src="//static.opentok.com/webrtc/v2.2/js/TB.min.js"></script>

<meta charset="UTF-8">
<meta http-equiv="content-type" content="text/html;charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="chrome=1">
<link href='https://fonts.googleapis.com/css?family=Muli:300,400' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="//tokbox.com/css/shared/fonts.css" />
<link rel="stylesheet" href="/vendors/fontAwesome/css/font-awesome.css" />
<link rel="stylesheet" href="/vendors/bootstrap/css/bootstrap.min.css" />

<script src="//code.jquery.com/jquery-1.10.2.min.js" type="text/javascript"></script>
<script src="/vendors/bootstrap/js/bootstrap.js"></script>


<div class="container">

  <div id="streams_container">
    <div class="streamContainer" id="myPublisherContainer">
      <div id="myPublisher"></div>
    </div>
  </div>

  <div id="controlsContainer">
    <div class="controlsBody">
      <div id="controlOptions" class="optionContainer">
        <a href="http://tokbox.com/?utm_source=opentokrtc&amp;utm_medium=web&amp;utm_campaign=webrtc" id="opentokLogo" target="_blank">
      <img src="/img/img-opentok-logo.png" alt="opentok transparent logo">
    </a>
    <div id="controlOptionsRight">
      <a href= "mailto:langlearn@langlearn.com?subject=chat%20Feedback" id="mailButton" data-tooltip-title="Send Feedback!" class="controlOption option">
      </a>
      <div id="filtersButton" data-tooltip-title = "Filters" class="controlOption option popover-dismiss" data-toggle="popover" data-placement="top" data-html="true" title="Filters" data-content="<ul id='filtersList'><li><button data-value='Sepia' type='button'>Sepia</button></li><li><button data-value='Invert' type='button'>Inverted</button></li><li><button data-value='Grayscale' type='button'>Grayscale</button></li><li><button data-value='Blur' type='button'>Blur</button></li><li><button data-value='None' type='button'>None</button></li></ul>"></div>
      <div id="roomLinkButton" data-tooltip-title="Share Room Link!" title="Share Room Link!" class="controlOption option popover-dismiss" data-placement="top"  data-activity="roomLink">
      </div>
        <div id="recordButton" data-tooltip-title="hangup" class="controlOption option"data-activity="record">
        <%= form_tag(summary_path) do %>
          <%= hidden_field_tag(:rid, rid)%>
          <%= submit_tag("end", :class => "hangup")  %>
        <%end%>
      </div> 
      <div id="chatButton" data-tooltip-title="Text Chat" class="controlOption option no-after" data-activity="chat">
      </div>
      </div>
    </div>
      </div>
    </div>
  </div>
</div>

<script id = "chattrBaseTpl" type = "text/x-handlebars-template">
  <div id = 'chattr'> 
    <div id ='relative_wrapper'>
      <div id='chat_header' class='chat-header' > 
        <div><span></span><span></span><span></span></div> 
        <h4 id='roomId'></h4> 
      </div> 
      <div class='inner-chat'> 
        <p id = 'displayHelp'> Type /help for a list of commands 
        <ul id='messages'> 
        </ul> 
      </div> 
      <div class='chat-input-wrapper'> 
        <input type='text' id='chatInput' placeholder= 'Write here...'  /> 
      </div> 
    </div>
  </div>
</script>
<script id = "chattrChatTpl" type="text/x-handlebars-template">
  <li class="chat {{cls}}">
  <label>{{nickname}}</label>
  <p data-date="{{date}}" title="{{time}}">{{message}}</p>
</script>
<script id="chattrStatusTpl" type="text/x-handlebars-template">
  <li class = 'status'>
    <p><span class='oldName'>{{oldName}}</span> is now known as <span class='newName'>{{newName}}</span></p>
  </li>
</script>
<script id="chattrNewUserTpl" type="text/x-handlebars-template">
  <li class= "status newUser">
    <p><span>{{nickname}}</span> has joined the room</p>
  </li>
</script>
<script id="chattrUserLeaveTpl" type="text/x-handlebars-template">
  <li class= "status newUser">
    <p><span>{{nickname}}</span> has left the room</p>
  </li>
</script>
<script id="chattrUpdateTpl" type="text/x-handlebars-template">
  <li class="status {{cls}}">
  {{{text}}}
  </li>
</script>
<script id="chattrUserListTpl" type="text/x-handlebars-template">
  <p class='userList'>Users in this room right now</p>
  {{#users}}
  <p class = "userList {{last}}">- {{name}}</p>
  {{/users}}
</script>
<script id="chattrHelpTpl" type="text/x-handlebars-template">
  <p>Type <span>/name your_name</span> to change your display name</p> 
  <p>Type <span>/list</span> to see a list of users in the room</p> 
  <p>Type <span>/focus</span> to focus the room on yourself</p>
  <p>Type <span>/unfocus</span> to take focus away from any focussed people in the room</p>
  <p class='last'>Type <span>/help</span> to see a list of commands</p>
</script>
<script id="chattrNameExistsTpl" type="text/x-handlebars-template">
  <p>User <span>{{newName}}</span> already exists. Please choose another name.</p>
</script>
<script id="chattrFocusTpl" type="text/x-handlebars-template">
  <li class="status">
    <p>User <span>{{nick}}</span> now has focus.</p>
  </li>
</script>
<script id="chattrUnfocusTpl" type="text/x-handlebars-template">
  <li class="status">
    <p>Focus has been removed.</p>
  </li>
</script>


<script id="userStreamTemplate" type="text/x-handlebars-template">
  <div class="streamContainer {{id}}" data-connectionid="{{connectionId}}">
    <div id="{{id}}"></div>
    <div class="flagUser" data-streamconnection="{{id}}">Remove User</div>
  </div>
</script>

<link href='https://fonts.googleapis.com/css?family=Muli:300,400' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="//tokbox.com/css/shared/fonts.css" />
<link rel="stylesheet" href="/vendors/fontAwesome/css/font-awesome.css" />
<link rel="stylesheet" href="/vendors/bootstrap/css/bootstrap.min.css" />

<script src="//code.jquery.com/jquery-1.10.2.min.js" type="text/javascript"></script>
<script src="/vendors/bootstrap/js/bootstrap.js"></script>


<link rel="stylesheet" href="/css/room.css" />
<link rel="stylesheet" href="/css/OpenTokChattr.css" />
<script src="//static.opentok.com/v2.2/js/opentok.min.js"></script>
<script src="/vendors/handlebars.js" type="text/javascript"></script>
<script src="/js/layoutContainer.js" type="text/javascript"></script>
<script src="/vendors/jquery.event.ue.js" type="text/javascript"></script>
<script src="/vendors/jquery.udraggable.js" type="text/javascript"></script>
<script src="/vendors/ZeroClipboard/ZeroClipboard.min.js" type="text/javascript"></script>
<script src="/js/OpenTokChattr.js" type="text/javascript"></script>
<!-- <script src="/app.js" type="text/javascript"></script> -->
<script src="/js/room.js" type="text/javascript"></script>
<script type="text/javascript">
  var session = OT.initSession( "<%= apiKey %>", "<%= sid %>" );
  chattr = new OpenTokChattr("body","<%= rid %>",session,
 {"draggable": true,
  "startPosition":{
    x: startX,
    y: startY
  },
  "closeable": function(){
    $("#chattr").hide();
    $("#chatButton").removeClass("selected");
  }
 });
  room = new Room("<%= rid %>", session, "<%= token %>", chattr);
  var startX = $(window).width()-10-$("#chattr").width();
  var startY = $(window).height()-56-$("#chattr").height();
  $('#filtersButton').popover();
  $(".controlOption").each(function(){
    $(this).tooltip({
      title: $(this).data("tooltip-title"),
      placement: "top"
    });
  });
  $('body').on('click', function (e) {
    $('.popover-dismiss').each(function () {
        //the 'is' for buttons that trigger popups
        //the 'has' for icons within a button that triggers a popup
        if (!$(this).is(e.target) && $(this).has(e.target).length === 0 && $('.popover').has(e.target).length === 0) {
            $(this).popover('hide');
            $(this).removeClass('selected');
        }
    });
  });
  $("#roomLinkButton").popover({
    title: $(this).attr("title"),
    content: "<input id='roomLinkInput' type='text' value='"+window.location.origin+"/<%= rid %>' ><button id='copyButton'>Copy</button>",
    html: true
  });
  $("#roomLinkButton").on('shown.bs.popover', function(){
    var client = new ZeroClipboard($("#copyButton"));
    client.on("ready", function(readyEvent){
      client.on("copy", function(event){
        var clipboard = event.clipboardData;
        clipboard.setData( "text/plain", window.location.origin+"/<%= rid %>" );
      });
      client.on("aftercopy", function(event){
        $("#copyButton").html("Copied!");
      });
    });
  });
  $(".controlOption").click(function(){
    $(this).toggleClass("selected");
  });
</script>

app/views/streams/summary.html.erb
<div class="container padding-top--sm">
	<div class="row">
		<div class="col-xs-12">
		  <div class="panel-header">
		  	<h3>Chat summary</h3>
		  </div>
			<%if @stream.guest_id == nil %>
				<div class="panel-main">
					<p>You ended the call before a guest joined your chat. You can return to the homepage and host a call again, or speak with someone to practice your skills.</p>
				</div>
			<%else%>
				<%if current_user.id == @stream.guest_id %> 
					<div class="panel-main">
						<h4>We hope you enjoyed your chat with <%=@earner.first_name %></h4>
						<p>Call duartion: <%=@duration%> seconds</p>
						<p>Coins spent: <span><%= image_tag("dollar", :class => "svg-small") %></span><span> <%=@amount%></span></p>
						<p>Remaining balance: <span><%= image_tag("dollar", :class => "svg-small") %></span><span> <%=@spender.total_coins%></span></p>
					</div>
				<%elsif current_user.id == @stream.host_id%>
					<div class="panel-main">
						<h3>We hope you enjoyed your chat with <%=@spender.first_name %></h3>
						<p>Call duartion: <%=@duration%> seconds</p>
						<p>Coins earned: <span><%= image_tag("dollar", :class => "svg-small") %></span><span> <%=@amount%></span></p>
						<p>New balance: <span><%= image_tag("dollar", :class => "svg-small") %></span><span> <%=@earner.total_coins%></span></p>
					</div>
				<%end%>
			<%end%>
		</div>
 	</div>
</div>