config/routes.rb
Rails.application.routes.draw do

  patch 'users/:user_id/preference', to: 'users#preference',  as: "preference"

  get 'admin/index'

  get 'payments/new', as: "new_payment"

  post 'payments/create', as: "payments"

  resources :users, only: [:edit, :update, :show]

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  post '/room/:rid', to: 'streams#host', as: "host"

  get '/room/:rid', to: 'streams#guest', as: "guest"

  post '/summary', to: 'streams#summary', as: "summary"


  root 'welcome#index'

	get 'users/index'
  # get 'welcome/index'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="container">
		<div class="row">
			<div class="col-sm-4 col-md-3">
				<nav class="footer-nav">
					<ul>
						<li class="footer-link"><a href="">contact us</a></li>
						<li class="footer-link"><a href="">careers</a></li>
						<li class="footer-link"><a href="">blog</a></li>
					</ul>
				</nav>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-12">
				<p>&copy; 2016 speak easy</p>
			</div>
		</div>
	</div>
</footer>

app/views/layouts/_navigation.html.erb
<header class="nav-wrapper">
  <nav>
    <div class="container nav-top">
      <a class="navbar-brand" href="">speak easy</a>
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
          <li class="nav--item">
            <%= link_to 'Home', root_path, :class => "nav-link" %>
          </li>
          <li class="nav--item">
            <%= link_to 'Profile', user_path(current_user.id), :class => "nav-link" %>
          </li>
          <li class="nav--item">
            <%= link_to 'Sign out', sign_out_path, method: :delete, :class => "nav-link" %>
          </li>
        <% else %>    
          <li class="nav--item">
            <a href="#" data-toggle="modal" data-target="#signin-modal">Sign In</a>
          </li>
          <li class="nav--item">
            <a href="#" data-toggle="modal" data-target="#signup-modal">Sign Up</a>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

<div id="signin-modal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-md">
    <div class="modal-content">
      <div class="modal-body">
        <div id="clearance" class="sign-in">

          <%= render partial: '/sessions/form' %>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="signup-modal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-md">
    <div class="modal-content">
      <div class="modal-body">
        <div id="clearance" class="sign-up">
          <%= link_to "Signup with Facebook", '/auth/facebook', :class => "like-btn like-btn--fb" %>
          <div class="signin-separator">
            <span class="signin-separator--text">or</span>
            <hr>
          </div>
          <%= form_for User.new do |form| %>
          <%= render partial: '/users/form', object: form %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>speak easy</title>
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Londrina+Solid" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" >
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">

    <script src="https://js.braintreegateway.com/v2/braintree.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <%= Gon::Base.render_data %>

  </head>

  <body>
    <%= render partial: '/layouts/navigation' %>
    <div class="container">
      <div id="flash">
        <% flash.each do |key, value| %>
            <% if key = notice %>
              <div class="alert alert-success" role="alert"><div class="flash <%= key %>"><%= value %></div></div>
            <% elsif key = alert %>
              <div class="alert alert-danger" role="alert"><div class="flash <%= key %>"><%= value %></div></div>
            <%end %>
        <% end %>
      </div>
    </div>
    <%= yield %>

  <% if request.original_url.match(/room/).nil? %>
  
    <footer>
      <div class="container">
        <div class="col-sm-12">
          <div class="col-md-6 col-sm-6">
            <div class="contact-info">
              <h2 class="footer-title">Contact Info</h2>
              <div class="single">
                <i class="fa fa-map-marker"></i>
                <p>Jalan Kiara 5,<br> 
              Mont Kiara, KL 50480, Malaysia</p>
              </div>
              <div class="single">
                <i class="fa fa-phone"></i>
                <p>017 323 2389</p>
              </div>
              <div class="single">
                <i class="fa fa-envelope"></i>
                <p>info@speakeasy.com</p>
              </div>
            </div>
          </div>
      <div class="col-md-6 col-sm-6 left-border">
      <div class="navigation">
      <ul class="list-unstyled">
        <li><a href="http://centerend.com/" title="">About Us</a></li>
        <li><a href="http://centerend.com/" title="">Terms & Conditions</a></li>
        <li><a href="http://centerend.com/" title="">Privacy Policy</a></li>
        <li><a href="http://centerend.com/" title="">Career</a></li>
        <li><a href="http://centerend.com/" title="">Contact Us</a></li>
      </ul>
      </div>
      </div>
      <div class="clearfix"></div>
      <div class="copyright visible-sm visible-xs">
      <p>Copyrights &copy; 2016 <a href="http://nextbootstrap.com/" title="">speak easy</a></p>
      </div>
      </div>
      </div>
      </div>
      </footer>
      <% else %>
  <% end %> 


  </body>
</html>